
  [build]
  functions = "netlify/functions"  # Where serverless functions are stored
  publish = "chatbot-ui"  # Path to the frontend directory

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"  # Redirect API requests to Netlify functions
  status = 200
  force = true

